import React, { useState } from 'react';
import { 
  FileBarChart, 
  Download, 
  Trash2, 
  Plus, 
  Search, 
  Loader2, 
  CheckCircle, 
  Calendar,
  Filter,
  Eye,
  X
} from 'lucide-react';
import { CURRENT_USER } from '../constants';

interface Report {
  id: string;
  name: string;
  type: 'PDF' | 'CSV' | 'XLSX';
  generatedAt: string;
  generatedBy: string;
  size: string;
  status: 'Ready' | 'Processing' | 'Failed';
  description?: string;
}

const INITIAL_REPORTS: Report[] = [
  { 
    id: 'r-1', 
    name: 'Weekly Operations Report - Jan 15', 
    type: 'PDF', 
    generatedAt: '2025-01-15', 
    generatedBy: 'Alex Miller', 
    size: '1.2 MB', 
    status: 'Ready',
    description: 'Standard weekly summary of production and compliance metrics.'
  },
  { 
    id: 'r-2', 
    name: 'Q4 Financial Summary', 
    type: 'XLSX', 
    generatedAt: '2025-01-10', 
    generatedBy: 'Sarah Jenkins', 
    size: '850 KB', 
    status: 'Ready',
    description: 'End of year financial roll-up.'
  },
  { 
    id: 'r-3', 
    name: 'Compliance Audit Log 2024', 
    type: 'CSV', 
    generatedAt: '2025-01-05', 
    generatedBy: 'Alex Miller', 
    size: '4.5 MB', 
    status: 'Ready',
    description: 'Full audit trail export.'
  }
];

const Reports = () => {
  const [reports, setReports] = useState<Report[]>(INITIAL_REPORTS);
  const [isGenerating, setIsGenerating] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedType, setSelectedType] = useState<string>('ALL');
  const [viewingReport, setViewingReport] = useState<Report | null>(null);

  const handleGenerateReport = () => {
    setIsGenerating(true);
    // Simulate generation
    setTimeout(() => {
      const newReport: Report = {
        id: `r-${Date.now()}`,
        name: `Operations Snapshot - ${new Date().toLocaleDateString()}`,
        type: 'PDF',
        generatedAt: new Date().toLocaleDateString(),
        generatedBy: CURRENT_USER.name,
        size: '1.5 MB',
        status: 'Ready',
        description: 'On-demand system snapshot.'
      };
      setReports([newReport, ...reports]);
      setIsGenerating(false);
    }, 2000);
  };

  const handleDelete = (id: string) => {
    if (confirm('Are you sure you want to delete this report?')) {
      setReports(reports.filter(r => r.id !== id));
    }
  };

  const handleDownload = (report: Report) => {
    // Mock download logic
    const element = document.createElement("a");
    const content = `Report: ${report.name}\nGenerated By: ${report.generatedBy}\nDate: ${report.generatedAt}\n\n[Binary Data Placeholder]`;
    const file = new Blob([content], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = `${report.name.replace(/\s+/g, '_')}.txt`; // Simulating file
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const filteredReports = reports.filter(r => {
    const matchesSearch = r.name.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesType = selectedType === 'ALL' || r.type === selectedType;
    return matchesSearch && matchesType;
  });

  return (
    <div className="space-y-6 relative">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">Reports Center</h2>
          <p className="text-slate-500 mt-1">Generate, view, and manage operational intelligence reports.</p>
        </div>
        <button 
          onClick={handleGenerateReport} 
          disabled={isGenerating}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 shadow-sm flex items-center transition-colors disabled:opacity-70 disabled:cursor-not-allowed"
        >
          {isGenerating ? (
            <>
              <Loader2 size={16} className="mr-2 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Plus size={16} className="mr-2" />
              Generate New Report
            </>
          )}
        </button>
      </div>

      {/* Filters */}
      <div className="flex flex-col md:flex-row gap-4 bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
          <input 
            type="text" 
            placeholder="Search reports..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-9 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 w-full"
          />
        </div>
        <div className="flex gap-2">
          {['ALL', 'PDF', 'CSV', 'XLSX'].map(type => (
            <button
              key={type}
              onClick={() => setSelectedType(type)}
              className={`px-3 py-2 rounded-lg text-xs font-medium border transition-colors ${
                selectedType === type 
                  ? 'bg-blue-50 text-blue-700 border-blue-200' 
                  : 'bg-white text-gray-600 border-gray-200 hover:bg-gray-50'
              }`}
            >
              {type}
            </button>
          ))}
        </div>
      </div>

      {/* Reports List */}
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Report Name</th>
                <th className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Type</th>
                <th className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Generated</th>
                <th className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Size</th>
                <th className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Status</th>
                <th className="px-6 py-3 text-right text-xs font-semibold text-gray-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {filteredReports.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-6 py-8 text-center text-gray-500 text-sm">
                    No reports found matching your criteria.
                  </td>
                </tr>
              ) : (
                filteredReports.map((report) => (
                  <tr key={report.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-6 py-4">
                      <div className="flex items-start">
                        <div className="p-2 bg-slate-100 text-slate-600 rounded-lg mr-3 mt-0.5">
                          <FileBarChart size={18} />
                        </div>
                        <div>
                          <p className="text-sm font-medium text-gray-900">{report.name}</p>
                          {report.description && (
                            <p className="text-xs text-gray-500 mt-0.5">{report.description}</p>
                          )}
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-gray-100 text-gray-800 border border-gray-200 font-mono">
                        {report.type}
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex flex-col">
                        <span className="text-sm text-gray-900 flex items-center">
                          <Calendar size={12} className="mr-1.5 text-gray-400" />
                          {report.generatedAt}
                        </span>
                        <span className="text-xs text-gray-500 mt-0.5 ml-4">by {report.generatedBy}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-500 font-mono">{report.size}</td>
                    <td className="px-6 py-4">
                      {report.status === 'Ready' ? (
                        <span className="inline-flex items-center text-xs font-medium text-green-700 bg-green-50 px-2 py-1 rounded-full border border-green-200">
                          <CheckCircle size={10} className="mr-1" /> Ready
                        </span>
                      ) : (
                         <span className="inline-flex items-center text-xs font-medium text-blue-700 bg-blue-50 px-2 py-1 rounded-full border border-blue-200">
                          <Loader2 size={10} className="mr-1 animate-spin" /> Processing
                        </span>
                      )}
                    </td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex justify-end space-x-2">
                        <button 
                          onClick={() => setViewingReport(report)}
                          className="p-1.5 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded transition-colors"
                          title="View"
                        >
                          <Eye size={16} />
                        </button>
                        <button 
                          onClick={() => handleDownload(report)}
                          className="p-1.5 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded transition-colors"
                          title="Download"
                        >
                          <Download size={16} />
                        </button>
                        <button 
                          onClick={() => handleDelete(report.id)}
                          className="p-1.5 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded transition-colors"
                          title="Delete"
                        >
                          <Trash2 size={16} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Report View Modal */}
      {viewingReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6" style={{ margin: 0 }}>
          <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm transition-opacity" onClick={() => setViewingReport(null)} />
          <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-4xl h-[85vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200">
             {/* Modal Header */}
             <div className="flex-none px-6 py-4 border-b border-gray-100 flex justify-between items-center bg-white z-20">
                <div className="flex items-center space-x-4">
                   <div className="p-2.5 bg-blue-50 text-blue-600 rounded-xl">
                      <FileBarChart size={24} />
                   </div>
                   <div>
                      <h3 className="text-lg font-bold text-gray-900 leading-tight">{viewingReport.name}</h3>
                      <p className="text-sm text-gray-500 mt-0.5 flex items-center">
                        <span className="font-medium text-gray-700">{viewingReport.generatedBy}</span>
                        <span className="mx-2 text-gray-300">•</span>
                        <span>{viewingReport.generatedAt}</span>
                        <span className="mx-2 text-gray-300">•</span>
                        <span>{viewingReport.size}</span>
                        <span className="mx-2 text-gray-300">•</span>
                        <span className="bg-gray-100 text-gray-700 px-1.5 py-0.5 rounded text-xs font-mono font-medium">{viewingReport.type}</span>
                      </p>
                   </div>
                </div>
                <div className="flex items-center space-x-2">
                   <button onClick={() => setViewingReport(null)} className="p-2 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors">
                      <X size={24} />
                   </button>
                </div>
             </div>

             {/* Modal Body - Mock Content Preview */}
             <div className="flex-1 overflow-y-auto bg-slate-50 p-8">
                <div className="bg-white shadow-sm border border-gray-200 min-h-[600px] p-12 mx-auto max-w-3xl flex flex-col">
                   {/* Letterhead */}
                   <div className="flex justify-between items-start mb-12 border-b border-gray-100 pb-8">
                      <div>
                        <h1 className="text-2xl font-bold text-slate-900">Tripleswitch Brewing</h1>
                        <p className="text-sm text-slate-500 mt-1">Operational Intelligence Division</p>
                      </div>
                      <div className="text-right">
                        <div className="text-sm font-bold text-slate-900 mb-1">CONFIDENTIAL</div>
                        <div className="text-xs text-slate-400">Report ID: {viewingReport.id.toUpperCase()}</div>
                      </div>
                   </div>

                   {/* Title */}
                   <div className="text-center mb-10">
                     <h2 className="text-3xl font-bold text-slate-900 mb-2">{viewingReport.name}</h2>
                     <p className="text-slate-500 italic">Generated on {viewingReport.generatedAt}</p>
                   </div>

                   {/* Content Sections */}
                   <div className="space-y-10">
                      <section>
                         <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-4 border-b pb-2">1. Executive Summary</h3>
                         <p className="text-sm text-slate-600 leading-relaxed text-justify">
                            This report aggregates key performance indicators across production, compliance, and logistics for the current reporting period. 
                            Overall operational efficiency stands at <strong>94%</strong>, with a 2.3% increase in throughput compared to the previous cycle. 
                            All regulatory filings for TTB are up to date, with zero flagged compliance incidents.
                         </p>
                      </section>

                      <section>
                         <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-4 border-b pb-2">2. Key Metrics Analysis</h3>
                         <div className="grid grid-cols-2 gap-6">
                            <div className="bg-gray-50 p-4 rounded-lg border border-gray-100">
                               <p className="text-xs text-slate-500 uppercase mb-1">Production Volume</p>
                               <p className="text-xl font-bold text-slate-900">4,250 Bbls</p>
                               <p className="text-xs text-green-600 mt-1 flex items-center">
                                  <span className="font-medium">+5.2%</span> vs last month
                               </p>
                            </div>
                            <div className="bg-gray-50 p-4 rounded-lg border border-gray-100">
                               <p className="text-xs text-slate-500 uppercase mb-1">Quality Assurance</p>
                               <p className="text-xl font-bold text-slate-900">99.8% Pass</p>
                               <p className="text-xs text-slate-500 mt-1">
                                  2 minor deviations corrected
                               </p>
                            </div>
                            <div className="bg-gray-50 p-4 rounded-lg border border-gray-100">
                               <p className="text-xs text-slate-500 uppercase mb-1">Inventory Turnover</p>
                               <p className="text-xl font-bold text-slate-900">14 Days</p>
                               <p className="text-xs text-green-600 mt-1">
                                  Optimal range
                               </p>
                            </div>
                            <div className="bg-gray-50 p-4 rounded-lg border border-gray-100">
                               <p className="text-xs text-slate-500 uppercase mb-1">Compliance Score</p>
                               <p className="text-xl font-bold text-slate-900">100%</p>
                               <p className="text-xs text-slate-500 mt-1">
                                  Audit ready
                               </p>
                            </div>
                         </div>
                      </section>

                      <section>
                         <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-4 border-b pb-2">3. Recommendations</h3>
                         <ul className="list-disc pl-5 space-y-2 text-sm text-slate-600">
                            <li>Prioritize scheduling for Tank 4 maintenance cycle to prevent downstream bottlenecks.</li>
                            <li>Review Q1 hop contracts against current utilization rates to optimize inventory holding costs.</li>
                            <li>Initiate refresher training for new hires on restricted document handling protocols.</li>
                         </ul>
                      </section>
                   </div>
                   
                   <div className="mt-auto pt-12 text-center">
                      <p className="text-xs text-slate-300">End of Report • {viewingReport.id} • Tripleswitch OS</p>
                   </div>
                </div>
             </div>

             {/* Modal Footer */}
             <div className="flex-none px-6 py-4 border-t border-gray-100 bg-white flex justify-end space-x-3">
               <button onClick={() => setViewingReport(null)} className="px-4 py-2 border border-gray-300 rounded-lg text-sm font-medium text-slate-700 hover:bg-gray-50 transition-colors">
                 Close View
               </button>
               <button onClick={() => handleDownload(viewingReport)} className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 shadow-sm flex items-center transition-colors">
                 <Download size={16} className="mr-2" /> Download Full Report
               </button>
             </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Reports;